<?php

namespace Database\Seeders;

use App\Models\Surah;
use Illuminate\Database\Seeder;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        $surahs = [
            [1, 'الفاتحة', 'Al-Fatihah', 'The Opening', 'meccan', 7],
            [2, 'البقرة', 'Al-Baqarah', 'The Cow', 'medinan', 286],
            [3, 'آل عمران', 'Aal-Imran', 'The Family of Imran', 'medinan', 200],
            [4, 'النساء', 'An-Nisa', 'The Women', 'medinan', 176],
            [5, 'المائدة', 'Al-Maidah', 'The Table Spread', 'medinan', 120],
            [6, 'الأنعام', 'Al-Anam', 'The Cattle', 'meccan', 165],
            [7, 'الأعراف', 'Al-Araf', 'The Heights', 'meccan', 206],
            [8, 'الأنفال', 'Al-Anfal', 'The Spoils of War', 'medinan', 75],
            [9, 'التوبة', 'At-Tawbah', 'The Repentance', 'medinan', 129],
            [10, 'يونس', 'Yunus', 'Jonah', 'meccan', 109],
            [11, 'هود', 'Hud', 'Hud', 'meccan', 123],
            [12, 'يوسف', 'Yusuf', 'Joseph', 'meccan', 111],
            [13, 'الرعد', 'Ar-Rad', 'The Thunder', 'medinan', 43],
            [14, 'إبراهيم', 'Ibrahim', 'Abraham', 'meccan', 52],
            [15, 'الحجر', 'Al-Hijr', 'The Rocky Tract', 'meccan', 99],
            [16, 'النحل', 'An-Nahl', 'The Bee', 'meccan', 128],
            [17, 'الإسراء', 'Al-Isra', 'The Night Journey', 'meccan', 111],
            [18, 'الكهف', 'Al-Kahf', 'The Cave', 'meccan', 110],
            [19, 'مريم', 'Maryam', 'Mary', 'meccan', 98],
            [20, 'طه', 'Ta-Ha', 'Ta-Ha', 'meccan', 135],
            [21, 'الأنبياء', 'Al-Anbiya', 'The Prophets', 'meccan', 112],
            [22, 'الحج', 'Al-Hajj', 'The Pilgrimage', 'medinan', 78],
            [23, 'المؤمنون', 'Al-Muminun', 'The Believers', 'meccan', 118],
            [24, 'النور', 'An-Nur', 'The Light', 'medinan', 64],
            [25, 'الفرقان', 'Al-Furqan', 'The Criterion', 'meccan', 77],
            [26, 'الشعراء', 'Ash-Shuara', 'The Poets', 'meccan', 227],
            [27, 'النمل', 'An-Naml', 'The Ant', 'meccan', 93],
            [28, 'القصص', 'Al-Qasas', 'The Stories', 'meccan', 88],
            [29, 'العنكبوت', 'Al-Ankabut', 'The Spider', 'meccan', 69],
            [30, 'الروم', 'Ar-Rum', 'The Romans', 'meccan', 60],
            [31, 'لقمان', 'Luqman', 'Luqman', 'meccan', 34],
            [32, 'السجدة', 'As-Sajdah', 'The Prostration', 'meccan', 30],
            [33, 'الأحزاب', 'Al-Ahzab', 'The Combined Forces', 'medinan', 73],
            [34, 'سبأ', 'Saba', 'Sheba', 'meccan', 54],
            [35, 'فاطر', 'Fatir', 'The Originator', 'meccan', 45],
            [36, 'يس', 'Ya-Sin', 'Ya-Sin', 'meccan', 83],
            [37, 'الصافات', 'As-Saffat', 'Those Who Set the Ranks', 'meccan', 182],
            [38, 'ص', 'Sad', 'Sad', 'meccan', 88],
            [39, 'الزمر', 'Az-Zumar', 'The Troops', 'meccan', 75],
            [40, 'غافر', 'Ghafir', 'The Forgiver', 'meccan', 85],
            [41, 'فصلت', 'Fussilat', 'Explained in Detail', 'meccan', 54],
            [42, 'الشورى', 'Ash-Shura', 'The Consultation', 'meccan', 53],
            [43, 'الزخرف', 'Az-Zukhruf', 'The Ornaments of Gold', 'meccan', 89],
            [44, 'الدخان', 'Ad-Dukhan', 'The Smoke', 'meccan', 59],
            [45, 'الجاثية', 'Al-Jathiyah', 'The Crouching', 'meccan', 37],
            [46, 'الأحقاف', 'Al-Ahqaf', 'The Wind-Curved Sandhills', 'meccan', 35],
            [47, 'محمد', 'Muhammad', 'Muhammad', 'medinan', 38],
            [48, 'الفتح', 'Al-Fath', 'The Victory', 'medinan', 29],
            [49, 'الحجرات', 'Al-Hujurat', 'The Rooms', 'medinan', 18],
            [50, 'ق', 'Qaf', 'Qaf', 'meccan', 45],
            [51, 'الذاريات', 'Adh-Dhariyat', 'The Winnowing Winds', 'meccan', 60],
            [52, 'الطور', 'At-Tur', 'The Mount', 'meccan', 49],
            [53, 'النجم', 'An-Najm', 'The Star', 'meccan', 62],
            [54, 'القمر', 'Al-Qamar', 'The Moon', 'meccan', 55],
            [55, 'الرحمن', 'Ar-Rahman', 'The Beneficent', 'medinan', 78],
            [56, 'الواقعة', 'Al-Waqiah', 'The Inevitable', 'meccan', 96],
            [57, 'الحديد', 'Al-Hadid', 'The Iron', 'medinan', 29],
            [58, 'المجادلة', 'Al-Mujadilah', 'The Pleading Woman', 'medinan', 22],
            [59, 'الحشر', 'Al-Hashr', 'The Exile', 'medinan', 24],
            [60, 'الممتحنة', 'Al-Mumtahanah', 'She That Is To Be Examined', 'medinan', 13],
            [61, 'الصف', 'As-Saff', 'The Ranks', 'medinan', 14],
            [62, 'الجمعة', 'Al-Jumuah', 'Friday', 'medinan', 11],
            [63, 'المنافقون', 'Al-Munafiqun', 'The Hypocrites', 'medinan', 11],
            [64, 'التغابن', 'At-Taghabun', 'Mutual Disillusion', 'medinan', 18],
            [65, 'الطلاق', 'At-Talaq', 'The Divorce', 'medinan', 12],
            [66, 'التحريم', 'At-Tahrim', 'The Prohibition', 'medinan', 12],
            [67, 'الملك', 'Al-Mulk', 'The Sovereignty', 'meccan', 30],
            [68, 'القلم', 'Al-Qalam', 'The Pen', 'meccan', 52],
            [69, 'الحاقة', 'Al-Haqqah', 'The Reality', 'meccan', 52],
            [70, 'المعارج', 'Al-Maarij', 'The Ascending Stairways', 'meccan', 44],
            [71, 'نوح', 'Nuh', 'Noah', 'meccan', 28],
            [72, 'الجن', 'Al-Jinn', 'The Jinn', 'meccan', 28],
            [73, 'المزمل', 'Al-Muzzammil', 'The Enshrouded One', 'meccan', 20],
            [74, 'المدثر', 'Al-Muddaththir', 'The Cloaked One', 'meccan', 56],
            [75, 'القيامة', 'Al-Qiyamah', 'The Resurrection', 'meccan', 40],
            [76, 'الإنسان', 'Al-Insan', 'The Man', 'medinan', 31],
            [77, 'المرسلات', 'Al-Mursalat', 'Those Sent Forth', 'meccan', 50],
            [78, 'النبأ', 'An-Naba', 'The Tidings', 'meccan', 40],
            [79, 'النازعات', 'An-Naziat', 'Those Who Drag Forth', 'meccan', 46],
            [80, 'عبس', 'Abasa', 'He Frowned', 'meccan', 42],
            [81, 'التكوير', 'At-Takwir', 'The Overthrowing', 'meccan', 29],
            [82, 'الانفطار', 'Al-Infitar', 'The Cleaving', 'meccan', 19],
            [83, 'المطففين', 'Al-Mutaffifin', 'The Defrauding', 'meccan', 36],
            [84, 'الانشقاق', 'Al-Inshiqaq', 'The Sundering', 'meccan', 25],
            [85, 'البروج', 'Al-Buruj', 'The Mansions of the Stars', 'meccan', 22],
            [86, 'الطارق', 'At-Tariq', 'The Nightcomer', 'meccan', 17],
            [87, 'الأعلى', 'Al-Ala', 'The Most High', 'meccan', 19],
            [88, 'الغاشية', 'Al-Ghashiyah', 'The Overwhelming', 'meccan', 26],
            [89, 'الفجر', 'Al-Fajr', 'The Dawn', 'meccan', 30],
            [90, 'البلد', 'Al-Balad', 'The City', 'meccan', 20],
            [91, 'الشمس', 'Ash-Shams', 'The Sun', 'meccan', 15],
            [92, 'الليل', 'Al-Layl', 'The Night', 'meccan', 21],
            [93, 'الضحى', 'Ad-Duha', 'The Morning Hours', 'meccan', 11],
            [94, 'الشرح', 'Ash-Sharh', 'The Relief', 'meccan', 8],
            [95, 'التين', 'At-Tin', 'The Fig', 'meccan', 8],
            [96, 'العلق', 'Al-Alaq', 'The Clot', 'meccan', 19],
            [97, 'القدر', 'Al-Qadr', 'The Power', 'meccan', 5],
            [98, 'البينة', 'Al-Bayyinah', 'The Clear Proof', 'medinan', 8],
            [99, 'الزلزلة', 'Az-Zalzalah', 'The Earthquake', 'medinan', 8],
            [100, 'العاديات', 'Al-Adiyat', 'The Courser', 'meccan', 11],
            [101, 'القارعة', 'Al-Qariah', 'The Calamity', 'meccan', 11],
            [102, 'التكاثر', 'At-Takathur', 'The Rivalry in World Increase', 'meccan', 8],
            [103, 'العصر', 'Al-Asr', 'The Declining Day', 'meccan', 3],
            [104, 'الهمزة', 'Al-Humazah', 'The Traducer', 'meccan', 9],
            [105, 'الفيل', 'Al-Fil', 'The Elephant', 'meccan', 5],
            [106, 'قريش', 'Quraysh', 'Quraysh', 'meccan', 4],
            [107, 'الماعون', 'Al-Maun', 'The Small Kindnesses', 'meccan', 7],
            [108, 'الكوثر', 'Al-Kawthar', 'The Abundance', 'meccan', 3],
            [109, 'الكافرون', 'Al-Kafirun', 'The Disbelievers', 'meccan', 6],
            [110, 'النصر', 'An-Nasr', 'The Divine Support', 'medinan', 3],
            [111, 'المسد', 'Al-Masad', 'The Palm Fiber', 'meccan', 5],
            [112, 'الإخلاص', 'Al-Ikhlas', 'The Sincerity', 'meccan', 4],
            [113, 'الفلق', 'Al-Falaq', 'The Daybreak', 'meccan', 5],
            [114, 'الناس', 'An-Nas', 'Mankind', 'meccan', 6],
        ];

        foreach ($surahs as [$number, $arabic, $transliterated, $english, $revelationType, $versesCount]) {
            Surah::updateOrCreate(
                ['number' => $number],
                [
                    'name_arabic' => $arabic,
                    'name_transliterated' => $transliterated,
                    'name_english' => $english,
                    'revelation_type' => $revelationType,
                    'verses_count' => $versesCount,
                ]
            );
        }
    }
}